"""Tests for schema extractor — cross-language edge detection."""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from rtfm.core.types import ET_DEPENDS_ENV, ET_GENERATED_BY, ET_PROVIDES_API, ET_CONSUMES_API
from rtfm.extractors.schema_extractor import (
    extract,
    _extract_ts_env,
    _check_generated_marker,
    _find_generator_in_header,
    _extract_proto,
    _extract_graphql,
)


@pytest.fixture
def project_root(tmp_path):
    return tmp_path


class TestOpenAPIExtraction:
    def test_extracts_endpoints_from_openapi_yaml(self, project_root):
        schema = project_root / "api" / "openapi.yaml"
        schema.parent.mkdir(parents=True)
        schema.write_text("""
openapi: "3.0.0"
info:
  title: Test API
paths:
  /users:
    get:
      operationId: listUsers
    post:
      operationId: createUser
  /users/{id}:
    get:
      operationId: getUser
""")
        result = extract(schema, project_root, {})
        # 1 schema node + 3 endpoint nodes
        assert len(result.nodes) == 4
        assert any(n["id"] == "schema::GET /users" for n in result.nodes)
        assert any(n["id"] == "schema::POST /users" for n in result.nodes)
        assert any(n["id"] == "schema::GET /users/{id}" for n in result.nodes)

    def test_extracts_endpoints_from_openapi_json(self, project_root):
        schema = project_root / "api.json"
        schema.write_text(json.dumps({
            "openapi": "3.0.0",
            "paths": {
                "/health": {"get": {"operationId": "healthCheck"}},
            },
        }))
        result = extract(schema, project_root, {})
        assert len(result.nodes) == 2
        assert any(n["id"] == "schema::GET /health" for n in result.nodes)

    def test_skips_non_openapi_yaml(self, project_root):
        config = project_root / "config.yaml"
        config.write_text("database:\n  host: localhost\n")
        result = extract(config, project_root, {})
        assert len(result.nodes) == 0

    def test_skips_invalid_json(self, project_root):
        bad = project_root / "broken.json"
        bad.write_text("{not valid json")
        result = extract(bad, project_root, {})
        assert len(result.nodes) == 0


class TestTypeScriptEnvExtraction:
    def test_extracts_process_env(self, project_root):
        ts_file = project_root / "src" / "config.ts"
        ts_file.parent.mkdir(parents=True)
        ts_file.write_text("""
const dbUrl = process.env.DATABASE_URL;
const port = process.env.PORT;
const secret = process.env.JWT_SECRET;
""")
        result = extract(ts_file, project_root, {})
        env_edges = [e for e in result.edges if e["edge_type"] == ET_DEPENDS_ENV]
        assert len(env_edges) == 3
        targets = {e["target"] for e in env_edges}
        assert "config::env_var::DATABASE_URL" in targets
        assert "config::env_var::PORT" in targets
        assert "config::env_var::JWT_SECRET" in targets

    def test_extracts_import_meta_env(self, project_root):
        ts_file = project_root / "src" / "vite.ts"
        ts_file.parent.mkdir(parents=True)
        ts_file.write_text("const api = import.meta.env.VITE_API_URL;\n")
        result = extract(ts_file, project_root, {})
        env_edges = [e for e in result.edges if e["edge_type"] == ET_DEPENDS_ENV]
        assert len(env_edges) == 1
        assert env_edges[0]["target"] == "config::env_var::VITE_API_URL"

    def test_deduplicates_same_env_var(self, project_root):
        ts_file = project_root / "app.ts"
        ts_file.write_text("""
const a = process.env.API_KEY;
const b = process.env.API_KEY;
""")
        result = extract(ts_file, project_root, {})
        env_edges = [e for e in result.edges if e["edge_type"] == ET_DEPENDS_ENV]
        assert len(env_edges) == 1


class TestGeneratedMarkerDetection:
    def test_detects_generated_marker(self, project_root):
        gen_file = project_root / "generated" / "types.ts"
        gen_file.parent.mkdir(parents=True)
        gen_file.write_text("// @generated by scripts/codegen.py\nexport type User = {};\n")
        result = extract(gen_file, project_root, {})
        gen_edges = [e for e in result.edges if e["edge_type"] == ET_GENERATED_BY]
        assert len(gen_edges) == 1
        assert gen_edges[0]["target"] == "scripts/codegen.py"

    def test_detects_do_not_edit_marker(self, project_root):
        gen_file = project_root / "models.ts"
        gen_file.write_text("/* DO NOT EDIT - Generated by tools/gen.ts */\n")
        result = extract(gen_file, project_root, {})
        gen_edges = [e for e in result.edges if e["edge_type"] == ET_GENERATED_BY]
        assert len(gen_edges) == 1
        assert gen_edges[0]["target"] == "tools/gen.ts"

    def test_detects_via_configured_paths(self, project_root):
        gen_file = project_root / "src" / "generated" / "api.ts"
        gen_file.parent.mkdir(parents=True)
        gen_file.write_text("export const endpoint = '/users';\n")
        config = {"cross_language": {"generated_paths": ["src/generated/"]}}
        result = extract(gen_file, project_root, config)
        gen_edges = [e for e in result.edges if e["edge_type"] == ET_GENERATED_BY]
        assert len(gen_edges) == 1

    def test_no_marker_no_edge(self, project_root):
        normal = project_root / "src" / "app.ts"
        normal.parent.mkdir(parents=True)
        normal.write_text("export function main() {}\n")
        result = extract(normal, project_root, {})
        gen_edges = [e for e in result.edges if e["edge_type"] == ET_GENERATED_BY]
        assert len(gen_edges) == 0


class TestProtobufExtraction:
    def test_extracts_services_and_rpcs(self, project_root):
        proto = project_root / "api.proto"
        proto.write_text("""
syntax = "proto3";

service UserService {
  rpc GetUser (GetUserRequest) returns (User);
  rpc ListUsers (ListUsersRequest) returns (UserList);
}

service AuthService {
  rpc Login (LoginRequest) returns (Token);
}
""")
        result = extract(proto, project_root, {})
        # 1 schema node + 3 rpc nodes
        assert len(result.nodes) == 4
        assert any(n["id"] == "schema::UserService/GetUser" for n in result.nodes)
        assert any(n["id"] == "schema::UserService/ListUsers" for n in result.nodes)
        assert any(n["id"] == "schema::AuthService/Login" for n in result.nodes)


class TestGraphQLExtraction:
    def test_extracts_query_fields(self, project_root):
        gql = project_root / "schema.graphql"
        gql.write_text("""
type Query {
  user(id: ID!): User
  users: [User!]!
}

type Mutation {
  createUser(input: CreateUserInput!): User
}
""")
        result = extract(gql, project_root, {})
        # 1 schema node + 3 field nodes
        assert len(result.nodes) == 4
        assert any(n["id"] == "schema::Query.user" for n in result.nodes)
        assert any(n["id"] == "schema::Query.users" for n in result.nodes)
        assert any(n["id"] == "schema::Mutation.createUser" for n in result.nodes)


class TestFindGeneratorInHeader:
    def test_finds_generated_by_pattern(self):
        header = "// Generated by scripts/codegen.py\n"
        assert _find_generator_in_header(header) == "scripts/codegen.py"

    def test_finds_source_pattern(self):
        header = "/* Source: tools/generate.ts */\n"
        assert _find_generator_in_header(header) == "tools/generate.ts"

    def test_returns_none_for_no_match(self):
        header = "// Regular comment\n"
        assert _find_generator_in_header(header) is None


class TestProviders:
    def test_fastapi_route_decorator(self, project_root):
        py_file = project_root / "src" / "api.py"
        py_file.parent.mkdir(parents=True)
        py_file.write_text('''
from fastapi import FastAPI
app = FastAPI()

@app.get("/users/{user_id}")
def get_user(user_id: int):
    return {"id": user_id}

@app.post("/users")
def create_user(data: dict):
    return data
''')
        result = extract(py_file, project_root, {})
        provider_edges = [e for e in result.edges if e["edge_type"] == ET_PROVIDES_API]
        assert len(provider_edges) == 2
        targets = {e["target"] for e in provider_edges}
        assert "schema::GET /users/{*}" in targets
        assert "schema::POST /users" in targets

    def test_flask_route_with_methods(self, project_root):
        py_file = project_root / "src" / "views.py"
        py_file.parent.mkdir(parents=True)
        py_file.write_text('''
from flask import Flask
app = Flask(__name__)

@app.route("/items", methods=["POST"])
def create_item():
    pass
''')
        result = extract(py_file, project_root, {})
        provider_edges = [e for e in result.edges if e["edge_type"] == ET_PROVIDES_API]
        assert len(provider_edges) == 1
        assert provider_edges[0]["target"] == "schema::POST /items"

    def test_starlette_router(self, project_root):
        py_file = project_root / "routes.py"
        py_file.write_text('''
from starlette.routing import Router
router = Router()

@router.delete("/sessions/{session_id}")
async def delete_session(session_id: str):
    pass
''')
        result = extract(py_file, project_root, {})
        provider_edges = [e for e in result.edges if e["edge_type"] == ET_PROVIDES_API]
        assert len(provider_edges) == 1
        assert provider_edges[0]["target"] == "schema::DELETE /sessions/{*}"

    def test_no_routes_no_edges(self, project_root):
        py_file = project_root / "utils.py"
        py_file.write_text("def helper(): pass\n")
        result = extract(py_file, project_root, {})
        provider_edges = [e for e in result.edges if e["edge_type"] == ET_PROVIDES_API]
        assert len(provider_edges) == 0


class TestConsumers:
    def test_requests_get(self, project_root):
        py_file = project_root / "client.py"
        py_file.write_text('''
import requests
resp = requests.get("/api/users/123")
''')
        result = extract(py_file, project_root, {})
        consumer_edges = [e for e in result.edges if e["edge_type"] == ET_CONSUMES_API]
        assert len(consumer_edges) == 1
        assert consumer_edges[0]["target"] == "schema::GET /api/users/123"

    def test_httpx_post_with_url(self, project_root):
        py_file = project_root / "service.py"
        py_file.write_text('''
import httpx
httpx.post("https://api.example.com/orders")
''')
        result = extract(py_file, project_root, {})
        consumer_edges = [e for e in result.edges if e["edge_type"] == ET_CONSUMES_API]
        assert len(consumer_edges) == 1
        assert consumer_edges[0]["target"] == "schema::POST /orders"

    def test_fetch_in_typescript(self, project_root):
        ts_file = project_root / "src" / "api.ts"
        ts_file.parent.mkdir(parents=True)
        ts_file.write_text('''
const users = await fetch("/api/users");
const order = await fetch("/api/orders/456");
''')
        result = extract(ts_file, project_root, {})
        consumer_edges = [e for e in result.edges if e["edge_type"] == ET_CONSUMES_API]
        assert len(consumer_edges) == 2
        targets = {e["target"] for e in consumer_edges}
        assert "schema::GET /api/users" in targets
        assert "schema::GET /api/orders/456" in targets

    def test_axios_methods(self, project_root):
        ts_file = project_root / "client.ts"
        ts_file.write_text('''
axios.get("/users")
axios.delete("/users/123")
''')
        result = extract(ts_file, project_root, {})
        consumer_edges = [e for e in result.edges if e["edge_type"] == ET_CONSUMES_API]
        assert len(consumer_edges) == 2
        targets = {e["target"] for e in consumer_edges}
        assert "schema::GET /users" in targets
        assert "schema::DELETE /users/123" in targets

    def test_deduplicates_same_endpoint(self, project_root):
        py_file = project_root / "retry.py"
        py_file.write_text('''
import requests
requests.get("/health")
requests.get("/health")
''')
        result = extract(py_file, project_root, {})
        consumer_edges = [e for e in result.edges if e["edge_type"] == ET_CONSUMES_API]
        assert len(consumer_edges) == 1


class TestNormalizePath:
    def test_openapi_params(self):
        from rtfm.extractors.schema_extractor import _normalize_path
        assert _normalize_path("/users/{id}") == "/users/{*}"
        assert _normalize_path("/orgs/{org_id}/repos/{repo_id}") == "/orgs/{*}/repos/{*}"

    def test_express_params(self):
        from rtfm.extractors.schema_extractor import _normalize_path
        assert _normalize_path("/users/:id") == "/users/{*}"

    def test_template_params(self):
        from rtfm.extractors.schema_extractor import _normalize_path
        assert _normalize_path("/users/${userId}") == "/users/{*}"

    def test_no_params(self):
        from rtfm.extractors.schema_extractor import _normalize_path
        assert _normalize_path("/users") == "/users"

    def test_strips_trailing_slash(self):
        from rtfm.extractors.schema_extractor import _normalize_path
        assert _normalize_path("/users/") == "/users"
